FROM node:18-slim

# Instala Poppler, Canvas e dependências nativas para renderização de imagens
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  poppler-utils \
  libjpeg62-turbo-dev \
  libpng-dev \
  build-essential \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  librsvg2-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV PORT=3001
EXPOSE 3001

CMD ["npm", "run", "dev"]
