FROM node:18-slim

# Instala Poppler (pdfimages) e dependências mínimas para imagens
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  poppler-utils \
  libjpeg62-turbo-dev \
  libpng-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV PORT=3001
EXPOSE 3001

CMD ["npm", "run", "dev"]
